"""add answers

Revision ID: 12358653f73b
Revises: 4bc0afcfa455
Create Date: 2023-01-20 01:47:04.337093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "12358653f73b"
down_revision = "4bc0afcfa455"
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        CREATE TABLE answears (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            attempt_id integer REFERENCES quiz_attempts(id) NOT NULL,
            question_id integer REFERENCES questions(id) NOT NULL,
            answear text,
            is_correct boolean NOT NULL
        );
        """
    )


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        DROP TABLE answears;
        """
    )
