"""add question types

Revision ID: 13cd081c2f6c
Revises: b6e4d73949ea
Create Date: 2023-01-20 00:43:48.318741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13cd081c2f6c"
down_revision = "b6e4d73949ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        CREATE TABLE question_types (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            type varchar(255) NOT NULL UNIQUE
        );
        
        INSERT INTO question_types (type) 
        VALUES ('Single choice'), ('Multiple choice'), ('Open');
        """
    )


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        DROP TABLE question_types;
        """
    )
