"""add quizes

Revision ID: 30b6dad9a94d
Revises: ba3e188b2c5f
Create Date: 2023-01-20 01:01:58.249319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "30b6dad9a94d"
down_revision = "ba3e188b2c5f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        CREATE TABLE quizes (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name varchar(255) NOT NULL,
            author_id integer REFERENCES accounts(id) NOT NULL,
            created_at timestamp DEFAULT NOW(),
            category_id integer REFERENCES categories(id),
            course_id integer REFERENCES courses(id),
            difficulty_id integer REFERENCES difficulties(id),
            description text,
            password varchar(255) DEFAULT null,
            attempts int DEFAULT 1,
            time_open timestamp,
            time_close timestamp,
            time_to_complete interval DEFAULT '1H',
            UNIQUE ("name", "course_id")
        );  
        """
    )


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        DROP TABLE quizes;
        """
    )
