"""add quizes_questions

Revision ID: 3d78a59e2428
Revises: 30b6dad9a94d
Create Date: 2023-01-20 01:19:37.857426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3d78a59e2428"
down_revision = "30b6dad9a94d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        CREATE TABLE quizes_questions (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            quiz_id integer REFERENCES quizes(id) NOT NULL,
            question_id integer REFERENCES questions(id) NOT NULL
        );
        """
    )


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        DROP TABLE quizes_questions;
        """
    )
