"""add quiz_attempts

Revision ID: 4bc0afcfa455
Revises: b62cb9327a84
Create Date: 2023-01-20 01:43:33.596093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4bc0afcfa455"
down_revision = "b62cb9327a84"
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        CREATE TABLE quiz_attempts (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            quiz_id integer REFERENCES quizes(id) NOT NULL,
            student_id integer REFERENCES accounts(id) NOT NULL,
            score float NOT NULL,
            attempt integer,
            modified TIME,
            start_date TIME DEFAULT NOW(),
            end_date TIME
        );
        """
    )


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        DROP TABLE quiz_attempts;
        """
    )
