"""add grades

Revision ID: 74974b7c1798
Revises: f8e85388e2c8
Create Date: 2023-01-20 01:24:24.696994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "74974b7c1798"
down_revision = "f8e85388e2c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        CREATE TABLE grades (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name varchar(255) NOT NULL,
            grade float NOT NULL
        );
        
        INSERT INTO grades (name, grade) 
        VALUES ('Not Finished', 0),
            ('F', 1), ('F+', 1.5), 
            ('D', 2), ('D+', 2.5), 
            ('C', 3), ('C+', 3.5), 
            ('B', 4), ('B+', 4.5), 
            ('A', 5), ('A+', 5.5);
        """
    )


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        DROP TABLE grades;
        """
    )
