"""add questions

Revision ID: 74d34965241c
Revises: 13cd081c2f6c
Create Date: 2023-01-20 00:47:05.399366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "74d34965241c"
down_revision = "13cd081c2f6c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """      
        CREATE TABLE questions (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            author_id integer REFERENCES accounts(id) NOT NULL,
            points float DEFAULT 1,
            task_question text,
            task_description text,
            question_type varchar(255) REFERENCES question_types(type),
            possible_answers text ARRAY,
            correct_answer text ARRAY
        );
        """
    )


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """      
        DROP TABLE questions;
        """
    )
