"""role

Revision ID: 8439111210e4
Revises: b6e4d73949ea
Create Date: 2023-01-20 00:29:12.839554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8439111210e4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
    CREATE TABLE roles (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(255) NOT NULL
    );
    
    INSERT INTO roles (name) VALUES ('Administrator'), ('Moderator'), ('Tutor'), ('Student');
        """
    )
    pass


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        DROP TABLE roles;
        """
    )
    pass
