"""add course_grades

Revision ID: b62cb9327a84
Revises: 74974b7c1798
Create Date: 2023-01-20 01:28:48.508822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b62cb9327a84"
down_revision = "74974b7c1798"
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        CREATE TABLE course_grades (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            quiz_id integer REFERENCES quizes(id) NOT NULL,
            student_id integer REFERENCES accounts(id) NOT NULL,
            grade_id integer REFERENCES grades(id) NOT NULL
        );
        """
    )


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        DROP TABLE course_grades;
        """
    )
