"""add acounts table

Revision ID: b6e4d73949ea
Revises: 
Create Date: 2023-01-19 23:46:36.444158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b6e4d73949ea"
down_revision = "8439111210e4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
     CREATE TABLE accounts (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username varchar(255) UNIQUE NOT NULL,
        email varchar(255) UNIQUE NOT NULL,
        confirmed boolean DEFAULT false NOT NULL,
        blocked boolean DEFAULT false NOT NULL,
        last_time_active timestamp DEFAULT NOW(),
        password varchar(255) NOT NULL,
        role_id integer REFERENCES roles(id) NOT NULL
    );
        """
    )


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        DROP TABLE accounts;
        """
    )
    pass
