"""add courses

Revision ID: f9c8a032910d
Revises: 74d34965241c
Create Date: 2023-01-20 00:50:00.014420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f9c8a032910d"
down_revision = "74d34965241c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        CREATE TABLE courses (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name varchar NOT NULL,
            author_id integer REFERENCES accounts(id) NOT NULL,
            password varchar(255) DEFAULT null
        );
        """
    )


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        """
        DROP TABLE courses;
        """
    )
